
  /*******************************************************************
  * AgentServicesNoLogin.java
  * Generated by Backendless Corp.
  ********************************************************************/
		
package in.ezeshop.internal.backendAPI;

import com.backendless.Backendless;

import in.ezeshop.appbase.constants.AppConstants;


  public class InternalUserServicesNoLogin
{
    static final String SERVICE_NAME = "InternalUserServicesNoLogin";
    static final String SERVICE_VERSION_NAME = "1.0.0";
    static final String APP_VERSION = "v1";

    private static InternalUserServicesNoLogin ourInstance = new InternalUserServicesNoLogin();

    private InternalUserServicesNoLogin(  )
    {
    }

    public static InternalUserServicesNoLogin getInstance()
    {
        return ourInstance;
    }

    public static void initApplication()
    {
        Backendless.setUrl( AppConstants.BACKENDLESS_HOST );
        // if you invoke this sample inside of android application, you should use overloaded "initApp" with "context" argument
        Backendless.initApp( AppConstants.BACKENDLESS_APP_ID, AppConstants.ANDROID_SECRET_KEY, InternalUserServicesNoLogin.APP_VERSION );
    }

    public void setDeviceForInternalUserLogin(String loginId, String deviceId)
    {
        Object[] args = new Object[]{loginId, deviceId};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "setDeviceForInternalUserLogin", args );
    }

    public void resetInternalUserPassword(String userId, String secret1)
    {
        Object[] args = new Object[]{userId, secret1};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "resetInternalUserPassword", args );
    }
}
