
  /*******************************************************************
  * CustomerServices.java
  * Generated by Backendless Corp.
  ********************************************************************/
		
package in.ezeshop.customerbase.backendAPI;

import com.backendless.Backendless;


import java.util.List;

import in.ezeshop.appbase.constants.AppConstants;
import in.ezeshop.common.database.Cashback;
import in.ezeshop.common.database.CustAddress;
import in.ezeshop.common.database.CustomerOps;
import in.ezeshop.common.database.CustomerOrder;
import in.ezeshop.common.database.Merchants;
import in.ezeshop.common.database.Transaction;

  public class CustomerServices
{
    static final String SERVICE_NAME = "CustomerServices";
    static final String SERVICE_VERSION_NAME = "1.0.0";
    static final String APP_VERSION = "v1";

    private static CustomerServices ourInstance = new CustomerServices();

    private CustomerServices(  )
    {
    }

    public static CustomerServices getInstance()
    {
        return ourInstance;
    }

    public static void initApplication()
    {
        Backendless.setUrl( AppConstants.BACKENDLESS_HOST );
        // if you invoke this sample inside of android application, you should use overloaded "initApp" with "context" argument
        Backendless.initApp( AppConstants.BACKENDLESS_APP_ID, AppConstants.ANDROID_SECRET_KEY, CustomerServices.APP_VERSION );
    }

    public CustomerOrder createCustomerOrder(String mchntId, String addressId, String comments, java.util.List<String> prescripUrls)
    {
        Object[] args = new Object[]{mchntId,addressId,comments,prescripUrls};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "createCustomerOrder", args, CustomerOrder.class );
    }

    public java.util.List<Merchants> mchntsByDeliveryArea(String areadId)
    {
        Object[] args = new Object[]{areadId};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "mchntsByDeliveryArea", args, java.util.List.class );
    }

    public java.util.List<CustAddress> saveCustAddress(CustAddress addr, Boolean setAsDefault)
    {
        Object[] args = new Object[]{addr, setAsDefault};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "saveCustAddress", args, java.util.List.class );
    }

    public java.util.List<Cashback> getCashbacks(String custPrivateId, long updatedSince)
    {
        Object[] args = new Object[]{custPrivateId, updatedSince};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getCashbacks", args, java.util.List.class );
    }

    public java.util.List<Transaction> getTransactions(String custPrivateId, String whereClause)
    {
        Object[] args = new Object[]{custPrivateId, whereClause};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getTransactions", args, java.util.List.class );
    }

    public java.util.List<CustomerOps> getCustomerOps(java.lang.String privateId)
    {
        Object[] args = new Object[]{privateId};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "getCustomerOps", args, java.util.List.class );
    }

    /*public void changePin(String oldPin, String newPin, String cardNum)
    {
        Object[] args = new Object[]{oldPin, newPin, cardNum};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "changePin", args );
    }
    public Customers changeMobile(String verifyParam, String newMobile, String otp)
    {
        Object[] args = new Object[]{verifyParam, newMobile, otp};
        return Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "changeMobile", args, Customers.class );
    }*/
}