
  /*******************************************************************
  * AgentServicesNoLogin.java
  * Generated by Backendless Corp.
  ********************************************************************/
		
package in.ezeshop.customerbase.backendAPI;

  import com.backendless.Backendless;

  import in.ezeshop.appbase.constants.AppConstants;


  public class CustomerServicesNoLogin
{
    static final String SERVICE_NAME = "CustomerServicesNoLogin";
    static final String SERVICE_VERSION_NAME = "1.0.0";
    static final String APP_VERSION = "v1";

    private static CustomerServicesNoLogin ourInstance = new CustomerServicesNoLogin();

    private CustomerServicesNoLogin(  )
    {
    }

    public static CustomerServicesNoLogin getInstance()
    {
        return ourInstance;
    }

    public static void initApplication()
    {
        Backendless.setUrl( AppConstants.BACKENDLESS_HOST );
        // if you invoke this sample inside of android application, you should use overloaded "initApp" with "context" argument
        Backendless.initApp( AppConstants.BACKENDLESS_APP_ID, AppConstants.ANDROID_SECRET_KEY, CustomerServicesNoLogin.APP_VERSION );
    }

    public void resetCustomerPassword(String mobileNum, String secret)
    {
        Object[] args = new Object[]{mobileNum, secret};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "resetCustomerPassword", args );
    }

    public void enableCustAccount(String userId, String passwd, String rcvdOtp, String pin)
    {
        Object[] args = new Object[]{userId, passwd, rcvdOtp, pin};
        Backendless.CustomService.invoke( SERVICE_NAME, SERVICE_VERSION_NAME, "enableCustAccount", args );
    }
}
